spring.application.name=reservelib
books.provider.api-key=AIzaSyAvnA6FLGtyFkl72vEktwdQ5WgvGSCglz0
books.provider.base-url=https://www.googleapis.com/books/v1/volumes
books.search.publisher-keywords=\u043B\u0438\u0442\u0440\u0435\u0441,litres
yandex.maps.provider.api-key=f9a5890b-8915-40a4-86a5-060beeb4fde9
yandex.maps.provider.base-url=https://geocode-maps.yandex.ru/1.x/
