spring.application.name=reservelib
books.provider.api-key=AIzaSyAvnA6FLGtyFkl72vEktwdQ5WgvGSCglz0
books.provider.base-url=https://www.googleapis.com/books/v1/volumes
books.search.publisher-keywords=??????,litres